language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
  - gem update --system
  - gem install bundler
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  keep-history: true
  on:
    branch: master